### ISSUE TITLE
THREE.js 网络的json模型下载到本地，用JSONLoader加载的时候提示 invalid url wxfile://XXX

### ISSUE THREAD

**Issue by zfavourite99** [finscn/weapp-adapter#13]
THREE.js 网络的json模型下载到本地，用JSONLoader加载的时候提示 invalid url wxfile，这个问题能解吗？微信咋这么恶心呢？？？

**Comment by zfavourite99** [comment]
问题已解决

在XMLHttpRequest.js 里面 做了如下修改：
原代码为：
              wx.request({
                data,
                url: url,
                method: _method.get(this),
                header: header,
                responseType: responseType,
                success: onSuccess,
                fail: onFail
              })

修改为：
           if (url.indexOf('wxfile://') == 0) {
              wx.getFileSystemManager().readFile({
                filePath:url,
                encoding:'utf8',
                success:onSuccess,
                fail:onFail
              }) 
            } else {
              wx.request({
                data,
                url: url,
                method: _method.get(this),
                header: header,
                responseType: responseType,
                success: onSuccess,
                fail: onFail
              })
            }

**Comment by gigiwotou** [comment]
谢谢。这个问题我也遇到了。
