### ISSUE TITLE
不太理解Node.js实现的真实作用？

### ISSUE THREAD

**Issue by caochao** [finscn/weapp-adapter#8]
[关于Node.js的实现](https://github.com/finscn/weapp-adapter/blob/master/src/Node.js#L11)
我不太理解这里实现的appendChild, removeChild有什么实际意义？似乎什么都没做。仅仅是兼容浏览器dom操作移植到微信小游戏时防止报错吗？

**Comment by caochao** [comment]
我在移植的过程中的做法是直接将dom操作代码干掉。

**Comment by finscn** [comment]
你这种做法需要修改第三方的引擎/框架.  现在很多引擎框架都是开源的, 几乎每周都会有新版本. 
每次有新版本发布 你还要重新去修改. 太麻烦了.
