### ISSUE TITLE
XMLHttpRequest实现为什么要把ArrayBuffer转化为text?

### ISSUE THREAD

**Issue by caochao** [finscn/weapp-adapter#9]
three.js fbxloader以arrayuffer为responseType调用XMLHttpRequest，期望拿到arraybuffer数据，但是这里实现的XMLHttpRequest最后一定要把arraybuffer转化为text，不知道原因? 我有想改的冲动，想先听听前辈的实现想法。。。
![image](https://user-images.githubusercontent.com/1911170/39921614-284eccb6-554e-11e8-8486-4f1794a318f8.png)

**Comment by finscn** [comment]
因为XMLHttpRequest 规范里就是这么规定的.

**Comment by finscn** [comment]
具体来说 是这样的: 
当responseType=arraybuffer时, 你要通过 xhr.response 获得arraybuffer数据.
当responseType=text/json/""/xml时,  你才可以通过xhr.responseText来取数据.

如果three.js 内部如果用了`responseType=arraybuffer` , 那么它一定是用的`xhr.response`来取数据.

其实要不要存一份 arraybuffer对应的字符串到responseText里确实有待商榷的问题.
最新的规范好像是说 如果responseType=arraybuffer , 那么用户读取xhr.responseText时, 是要抛出异常的.
从这个角度来看, 也许确实没必要转.转了还影响性能 耗费内存.

**Comment by finscn** [comment]
@caochao , 我更新了一个新版本, 你看一下. 现在当 data 是arraybuffer时,  你再用 responseText 会抛出异常.
参考:  https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseText

**Comment by caochao** [comment]
感谢前辈那么晚还回复问题。重新追踪了源码，fbxloader确实是拿xhr.response来获得arraybuffer数据的。
因为我加载的是本地fbx，所以走的是readFile流程，这里判断判断responseType=arraybuffer时会将encoding参数设置为binary，然后onSuccess回调里返回的data是string类型。所以我碰到的总是是出瑞在这里。
![1526054593762](https://user-images.githubusercontent.com/1911170/39934277-f186d9aa-550a-11e8-9920-196e8e16bd43.jpg)

**Comment by finscn** [comment]
谢谢你报告的新问题. 我看一下.

**Comment by finscn** [comment]
@caochao 我又更新了一个版本, 麻烦测试一下. 谢谢了
